export enum Role {
  ADMINISTRATOR = 'ADMINISTRATOR',
  RESPONSIBLE = 'RESPONSIBLE',
  SCHOOL = 'SCHOOL',
  STUDENT = 'STUDENT',
}

export enum PaymentStatus {
  PENDING = 'PENDING',
  PAID = 'PAID',
  LATE = 'LATE',
  ANALYSIS = 'ANALYSIS',
  // CANCELED = 'CANCELED',
}
